version: '3.9'


services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - service-networks
    volumes:
      - "mongo-data:/data/db"
    expose:
      - ${MONGO_PORT}
networks:
  service-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: "local"
